apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mfaizan21/skydivers-backend:v0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: backend
  labels:
    app: backend
spec:
  service:
    host: backend
    name: backend
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      methods: ["GET","POST", "PUT", "DELETE"]
      accessStrategies:
        - handler: noop
      mutators: []
